### ISSUE TITLE
ClassCastException with parameterized Type

### ISSUE THREAD

**Issue by bpoussin** [antoinemeyer/mock-in-bean#7]
If we use generic on `@MockInBean` we have ClassCastException on line

https://github.com/antoinemeyer/mock-in-bean/blob/09c3a31481d89eb012c13707c35edbfbac28b25a/src/main/java/com/teketik/test/mockinbean/MockInBeanTestExecutionListener.java#L43

Because `definition.getResolvableType().getType()` return `java.lang.reflect.ParameterizedType` and not a class.

code must be change to check type and if returned value is instance of `java.lang.reflect.ParameterizedType` we must call
`((java.lang.reflect.ParameterizedType)definition.getResolvableType().getType()).getRawType()` to get Class

we can replace 
`final Class<?> mockOrSpyType = (Class<?>) definition.getResolvableType().getType();`

with
```
final Class<?> mockOrSpyType = getClassOfType(definition.getResolvableType().getType()); 

private Class<?> getClassOfType(Type type) {
    Type result = type;
    if (type instanceof ParameterizedType) {
        result = ((ParameterizedType)definition.getResolvableType().getType()).getRawType();
    }
    return (Class<?>)result;
```

**Comment by sviunnikov** [comment]
Yes. Unfortunately it does not work with generics. Can we make a MR and fix it?

**Comment by antoinemeyer** [comment]
Thanks a lot for reporting the issue!
This has been fixed by https://github.com/antoinemeyer/mock-in-bean/pull/8 and fix deployed to maven central under version `boot2-v1.3`.
